carsharing/api_app/urls.py
from django.conf.urls import url
from .views import SignupView, ChangePasswordView, UsersView, UserView, UserCarsView
from rest_framework.authtoken import views

app_name = 'api_app'
urlpatterns = [
    url(r'^login/$', views.obtain_auth_token),
    url(r'^signup/$', SignupView.as_view()),
    url(r'^change_password/$', ChangePasswordView.as_view()),
    url(r'^users/(?P<pk>\d+)/cars/$', UserCarsView.as_view()),
    url(r'^users/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^users/$', UsersView.as_view()),
]

carsharing/common_app/urls.py
from django.urls import path

from .views import HomeView, CarCreateView

app_name = 'common_app'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('car_create/', CarCreateView.as_view(), name='car_create')
]

carsharing/users_app/urls.py
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users_app'
urlpatterns = [

    path('signup/', views.SignUpFormView.as_view(), name='signup'),
    path('login/', views.SignInFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('update/', views.UserUpdateView.as_view(), name='update_user'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', views.UserDetailView.as_view(), name='user_detail'),

]

carsharing/templates/base.html
{% load staticfiles %}
{% load i18n %}

<!doctype html>
<html>
    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block meta %}{% endblock %}

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'vendors/jquery/jquery.min.js' %}"></script>

        <!-- Font awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
              integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns"
              crossorigin="anonymous">

        <!-- Bootstrap and Popper -->
        <link href="{% static 'vendors/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
        <script src="{% static 'vendors/bootstrap/js/popper.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}"></script>


        {% block style %}{% endblock %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet">


        <title>Carsharing | {% block title %}{% endblock %}</title>

        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <link rel="apple-touch-icon" href="{% static 'img/favicon.png' %}" type="image/png">

    </head>

    <body>
        {% block navbar %}
            <nav class="navbar navbar-expand-lg navbar-light border-bottom">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'common_app:home' %}"><strong>Carsharing</strong></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"
                            aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbar">
                        <ul class="navbar-nav ml-auto">
                            <div class="dropdown-divider"></div>
                            {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'common_app:car_create' %}">Добавить машину</a>
                                </li>
                                <div class="dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{ request.user.first_name }}
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'users_app:user_detail' %}">Настройки</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'users_app:logout' %}">Выйти</a>
                                  </div>
                                </div>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users_app:login' %}">Войти</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        {% endblock %}


        <div class="container">
            {% block content %} {% endblock %}
        </div>



        {% block footer %}{% endblock %}


        <!-- Optional JavaScript -->
        <script src="{% static 'js/main.js' %}"></script>

        {% block script %}{% endblock %}

    </body>
</html>