carsharing/api_app/urls.py
from django.conf.urls import url
from .views import SignupView, ChangePasswordView, UsersView, UserView, UserCarsView
from rest_framework.authtoken import views

app_name = 'api_app'
urlpatterns = [
    url(r'^login/$', views.obtain_auth_token),
    url(r'^signup/$', SignupView.as_view()),
    url(r'^change_password/$', ChangePasswordView.as_view()),
    url(r'^users/(?P<pk>\d+)/cars/$', UserCarsView.as_view()),
    url(r'^users/(?P<pk>\d+)/$', UserView.as_view()),
    url(r'^users/$', UsersView.as_view()),
]

carsharing/users_app/urls.py
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'users_app'
urlpatterns = [

    path('signup/', views.SignUpFormView.as_view(), name='signup'),
    path('login/', views.SignInFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('update/', views.UserUpdateView.as_view(), name='update_user'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', views.UserDetailView.as_view(), name='user_detail'),

]

carsharing/users_app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,
    PermissionsMixin)


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, language, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        user = self.model(email=self.normalize_email(email),
                          first_name=first_name,
                          language=language,)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, language, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(email,
                                password=password,
                                first_name=first_name,
                                language=language)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    language = models.CharField(max_length=2, choices=settings.LANGUAGES)
    email = models.EmailField(_('email address'), blank=False, unique=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'language']

    def __str__(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

carsharing/users_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import TextInput, EmailInput, Select
from django.utils.translation import ugettext_lazy as _

from .tasks import user_welcome

User = get_user_model()


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label=_(u"Пароль"),
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=True)

    class Meta:
        model = User
        fields = ("email", "first_name", "language")
        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'language': Select(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control'}),
            'password': TextInput(attrs={'class': 'form-control'}),
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 6:
            raise forms.ValidationError(_('Password too short'))
        return password

    def save(self, request=None, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
            # User notification
            user_welcome(user.id)

        return user

carsharing/users_app/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import ugettext_lazy as _
from django.views import View
from django.views.generic import FormView, UpdateView, DetailView

from .forms import UserCreationForm
from .models import User


class SignUpFormView(FormView):
    form_class = UserCreationForm
    success_url = reverse_lazy('common_app:home')
    template_name = "users_app/signup.html"

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(email=email, password=password)
        login(self.request, user)
        return super(SignUpFormView, self).form_valid(form)


class SignInFormView(FormView):
    form_class = AuthenticationForm
    template_name = "users_app/login.html"
    success_url = reverse_lazy('common_app:home')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super(SignInFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('common_app:home'))


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'users_app/password_change.html'
    form_valid_message = _("Your password was changed!")
    success_url = reverse_lazy('users_app:user_detail')


class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'users_app/password_reset.html'
    success_url = reverse_lazy('users_app:password_reset_done')
    email_template_name = 'users_app/emails/password_reset.html'


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'users_app/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'users_app/password_reset_confirm.html'
    success_url = reverse_lazy('common_app:home')
    form_valid_message = _("Your password was changed!")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self, *args, **kwargs):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['email', 'first_name', 'language']
    template_name = 'users_app/user_update.html'
    success_url = reverse_lazy('users_app:user_detail')

    def get_object(self, *args, **kwargs):
        return self.request.user

carsharing/templates/users_app/base.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/users_app.css' %}">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-light navbar-expand-sm border-bottom p-3 px-md-5 py-md-2">
        <a class="navbar-brand" href="/"><strong>Carsharing</strong></a>
        <ul class="navbar-nav ml-auto text-muted ">
            <li class="nav-item"><i class="fas fa-lock"></i><small class="pl-2 font-weight-normal">SSL Secure</small></li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <div class="login-wrapper mx-auto mt-sm-5 pt-4  p-sm-4">
        <div class="text-center font-weight-light">
            {% block form-title %}{% endblock %}
        </div>
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% for error in field.errors %}
                        <small><strong>{{ field.name }}</strong> - {{ error|escape }}</small><br>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <small>{{ error|escape }}</small><br>
                {% endfor %}
            </div>
        {% endif %}
        {% block form-body %}{% endblock %}
        {% block form-footer %}{% endblock %}
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/users_app.js' %}"></script>
{% endblock %}

carsharing/templates/users_app/login.html
{% extends "users_app/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}Login{% endblock %}

{% block form-title %}
    <h4>{% trans 'Sign in' %}</h4>
    <p>{% trans 'Please sign in for secure access to your account' %}.</p>
{% endblock %}

{% block form-body %}
    <form name="form" method="post" action="{% url 'users_app:login' %}" autocomplete="off">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <input type="email" required id="{{ form.username.id_for_label }}" class="form-control" name="{{ form.username.html_name }}">
                    <label for="{{ form.username.id_for_label }}">{% trans 'Email' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <input type="password" required id="{{ form.password.id_for_label }}" class="form-control" name="{{ form.password.html_name }}">
                    <label for="{{ form.password.id_for_label }}">{% trans 'Password' %}</label>
                    <a href="javascript:" id="eye"><i class="far fa-eye"></i></a>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans 'Sign In' %}</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block form-footer %}
    <div class="font-weight-light py-4">
        <div class="float-left">
            <a href="{% url 'users_app:password_reset' %}">{% trans 'Forgot your password' %}?</a>
        </div>
        <div class="float-right">
            <a href="{% url 'users_app:signup' %}">{% trans 'Sign up' %}</a>
        </div>
    </div>
{% endblock %}

carsharing/templates/users_app/password_change.html
{% extends "users_app/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans 'Set a new password' %}{% endblock %}

{% block form-title %}
    <h5>{% trans 'Enter your old and new passwords' %}</h5>
{% endblock %}

{% block form-body %}
    <form class="form" role="form" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <input type="password" required id="{{ form.old_password.id_for_label }}" class="form-control"
                           name="{{ form.old_password.html_name }}">
                    <label for="{{ form.old_password.id_for_label }}">{% trans 'Old password' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <input type="password" required id="{{ form.new_password1.id_for_label }}" class="form-control"
                           name="{{ form.new_password1.html_name }}">
                    <label for="{{ form.new_password1.id_for_label }}">{% trans 'New password' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <input type="password" required id="{{ form.new_password2.id_for_label }}" class="form-control"
                           name="{{ form.new_password2.html_name }}">
                    <label for="{{ form.new_password2.id_for_label }}">{% trans 'New password again' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

carsharing/templates/users_app/password_reset.html
{% extends "users_app/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block form-title %}
    <h4>{% trans "Let's find your account" %}</h4>
    <p>{% trans "Enter your email address and we'll send instructions on how to reset your password" %}</p>
{% endblock %}

{% block form-body %}
    <form name="form" action="{% url 'users_app:password_reset' %}" method="post" role="form">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <input type="email" required id="{{ form.email.id_for_label }}" class="form-control" name="{{ form.email.html_name }}">
                    <label for="{{ form.email.id_for_label }}">{% trans 'Email' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

carsharing/templates/users_app/password_reset_confirm.html
{% extends "users_app/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans 'Set a new password' %}{% endblock %}

{% block form-title %}
    <h5>{% trans 'Enter your new password' %}</h5>
{% endblock %}

{% block form-body %}
    <form class="form" role="form" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <input type="password" required id="{{ form.new_password1.id_for_label }}" class="form-control"
                           name="{{ form.new_password1.html_name }}">
                    <label for="{{ form.new_password1.id_for_label }}">{% trans 'New password' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <input type="password" required id="{{ form.new_password2.id_for_label }}" class="form-control"
                           name="{{ form.new_password2.html_name }}">
                    <label for="{{ form.new_password2.id_for_label }}">{% trans 'New password again' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

carsharing/templates/users_app/password_reset_done.html
{% extends "users_app/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block form-title %}
    {% blocktrans %}A password reset email has been sent to the entered email,
        if a user with such an email address exists.
    {% endblocktrans %}
{% endblock %}

carsharing/templates/users_app/signup.html
{% extends "users_app/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block form-title %}
    <h4>{% trans 'Sign up' %}</h4>
    {% url 'users_app:login' as login_url %}
    {% blocktrans %}
        <p>Create an account or <a href="{{ login_url }}">sign in</a></p>
    {% endblocktrans %}
{% endblock %}

{% block form-body %}
    <form name="form" method="post" action="{% url 'users_app:signup' %}" autocomplete="off">
        {% csrf_token %}
        <div class="row">
            <div class="col-12 pr-2">
                <div class="form-group">
                    {{ form.first_name }}
                    <label for="{{ form.first_name.id_for_label }}">{% trans 'First name' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    {{ form.email }}
                    <label for="{{ form.email.id_for_label }}">{% trans 'Email' %}</label>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <select name="{{ form.language.html_name }}"  class="form-control">
                        <option disabled selected>Выберите язык</option>
                        {% for x,y in form.fields.language.choices %}
                            <option value="{{ x }}">{{ y }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    {{ form.password }}
                    <label for="{{ form.password.id_for_label }}">{% trans 'Password' %}</label>
                    <a href="javascript:" id="eye"><i class="far fa-eye"></i></a>
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">{% trans 'Create my account' %}</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block form-footer %}
    <div class="text-center font-weight-light py-4">
        <span>{% trans 'You already have an account' %}?</span>
        <a href="{% url 'users_app:login' %}">{% trans 'Sign In' %}</a>
    </div>
{% endblock %}

carsharing/templates/users_app/user_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}User detail{% endblock %}

{% block content %}
<div class="wrapper mx-auto border">
    <h4 class="text-center pb-3">Информация о пользователе</h4>
    <div class="">
        <strong>E-mail: </strong>
        <span>{{ object.email }}</span>
    </div>
    <div class="">
        <strong>Имя: </strong>
        <span>{{ object.first_name }}</span>
    </div>
    <div class="">
        <strong>Язык: </strong>
        <span>{{ object.language }}</span>
    </div>
    <div class="text-center font-weight-light py-4">
        <div class="float-left">
            <a class="btn btn-primary" href="{% url 'users_app:update_user' %}">Изменить информацию</a>
        </div>
        <div class="float-right">
            <a class="btn btn-primary" href="{% url 'users_app:password_change' %}">Изменить пароль</a>
        </div>
    </div>
</div>
{% endblock %}

carsharing/templates/users_app/user_update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}User update{% endblock %}

{% block content %}

    <div class="wrapper mx-auto border">
        <h4 class="py-3 text-center">Изменить информацию о пользователе</h4>
        <form action="" method="post">
        {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <small><strong>{{ field.name }}</strong> - {{ error|escape }}</small><br>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <small>{{ error|escape }}</small><br>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="{{ form.email.id_for_label }}">Email:</label>
                <input type="text" name="{{ form.email.html_name }}" value="{{ form.email.value }}" class="form-control">
            </div>
            <div class="form-group">
                <label for="{{ form.first_name.id_for_label }}">Имя:</label>
                <input type="text" name="{{ form.first_name.html_name }}" value="{{ form.first_name.value }}" class="form-control">
            </div>
            <div class="form-group">
                <label for="{{ form.language.id_for_label }}">Язык:</label>
                <select name="{{ form.language.html_name }}" class="form-control">
                    {% for x,y in form.fields.language.choices %}
                    <option value="{{ x }}" {% if form.language.value == x %} selected{% endif %}>{{ y }}</option>
                    {% endfor %}
                </select>
            </div>

            <input type="submit" class="btn btn-primary">
        </form>
    </div>

{% endblock %}